# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_study', models.TextField()),
                ('programme', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('school_type', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(db_index=True, max_length=10)),
                ('state', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(db_index=True, max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School'),
        ),
    ]
